export const APP_VERSION = "тест-билд 0.2";

export const links = {
  github: "https://github.com/48rn2krftk-dev/fuel-rate-calc",
  email:
    "mailto:comrade.stalin@icloud.com?subject=Горячий%20простой%20—%20обратная%20связь",
  telegram: "https://t.me/drunken43spark",
  express:
    "https://xlnk.ms/open/profile/31871131-d6cb-581e-ba0b-35815e3e06e2",
  support: "https://tips.yandex.ru/guest/payment/3746623",
} as const;

export const uiText = {
  app: {
    eyebrow: "Рабочие инструменты теплотехника",
    title: "Уголок теплотехника",
    version: `Уголок теплотехника · ${APP_VERSION}`,
    connection: {
      checking: "Проверка",
      online: "Онлайн",
      offline: "Офлайн",
    },
    navigation: {
      quick: "Быстрый расчёт",
      summary: "Сумма",
      settings: "Ещё",
      all: "Все",
    },
  },
  common: {
    clear: "Очистить",
    clearAll: "Очистить всё",
    emptyValue: "—",
    save: "Сохранить",
    units: {
      hoursShort: "ч",
      kilograms: "кг",
      kilogramsPerHour: "кг/ч",
      minutesShort: "м",
    },
    result: {
      heatingTime: "Время прогрева",
      fuelUsed: "Израсходовано",
      fuelPerHour: "Расход в час",
    },
  },
  normComparison: {
    percentOfNorm: "% от нормы",
    matchesNorm: "Расход соответствует норме",
    reserve: "Резерв до нормы",
    overrun: "Перерасход относительно нормы",
    normativeFuelEnd: "Расчётный остаток при сдаче по нормативу",
  },
  saveResult: {
    dialogLabel: "Сохранение результата",
    title: "Сохранить результат",
    firstSlotDescription: "Задай название и сохрани первый слот.",
    existingSlotsDescription:
      "Можно перезаписать существующий слот или сохранить в новый.",
    close: "Закрыть",
    nameLabel: "Название сохранения",
    namePlaceholder: "Например 3ТЭ25К2М-697 секция 1",
    saveToSlot: (slot: number) => `Сохранить в слот ${slot}`,
    slotOverwritten: (slot: number) => `Слот ${slot} перезаписан`,
    savedToSlot: (slot: number) => `Сохранено в слот ${slot}`,
    overwriteSlot: (slot: number) => `Слот ${slot} — перезаписать`,
    saveToNewSlot: (slot: number) => `Слот ${slot} — сохранить в новый`,
    current: "Сейчас",
    emptySlot: "Новый свободный слот",
  },
  byTime: {
    title: "Расчёт по ведомости ф. ТХУ-3",
    description: "Введи время и данные о топливе из ведомости ТХУ-3.",
    startTime: "Начало прогрева",
    startTimePlaceholder: "0735 или 0101260735",
    endTime: "Окончание прогрева",
    endTimePlaceholder: "0910 или 0201260910",
    fuelStart: "Топливо при приёмке, кг",
    fuelEnd: "Топливо при сдаче, кг",
    fuelPlaceholder: "411,000",
    fuelEndPlaceholder: "371,000",
    ocr: "📷 Сканировать ТХУ-3",
    soon: "Скоро",
    nextDayQuestion:
      "Окончание не позже начала. Считать его временем следующих суток?",
    nextDayConfirm: "Да, следующие сутки",
    mixedDateError:
      "Если дата указана только в одном поле, она должна быть в поле начала.",
    fuelError:
      "Топливо при сдаче не может превышать топливо при приёмке.",
  },
  quick: {
    title: "Расчёт горячего простоя",
    description:
      "Выбери удобный способ ввода времени и укажи расход топлива.",
    durationMode: "По длительности",
    intervalMode: "Начало и конец",
    duration: "Время прогрева",
    durationPlaceholder: "2214 или 163559",
    fuelUsed: "Расход топлива, кг",
    fuelPlaceholder: "40,000",
    durationError:
      "Введи время в формате 22:14, 2214 или 1635:59.",
    fuelError:
      "Введи топливо от 0 до 9999,999 кг (не более трёх знаков после запятой).",
  },
  summary: {
    title: "Сложение прогревов",
    description:
      "Сложи несколько прогревов из сохранённых слотов или введи их вручную.",
    fuelStart: "Топливо в начале цепочки, кг (необязательно)",
    fuelStartPlaceholder: "411,000",
    fuelStartError: "Введи начальное топливо от 0 до 9999,999 кг.",
    fuelChainError:
      "Общий расход не может превышать топливо в начале цепочки.",
    heating: (index: number) => `Прогрев ${index}`,
    deleteHeating: (index: number) => `Удалить прогрев ${index}`,
    manual: "Вручную",
    fromSlot: "Из слота",
    savedCalculation: "Сохранённый расчёт",
    slotOption: (slot: number, title: string) => `Слот ${slot}: ${title}`,
    duration: "Время прогрева",
    durationPlaceholder: "2214 или 1635:59",
    fuelUsed: "Расход топлива, кг",
    fuelUsedPlaceholder: "40,000",
    durationError:
      "Введи время в формате 22:14, 2214 или 1635:59.",
    fuelError: "Введи топливо от 0 до 9999,999 кг.",
    addMore: "Добавить ещё",
    totalTime: "Общее время",
    totalFuel: "Общий расход",
    averageFuelPerHour: "Средний расход в час",
    actualFuelEnd: "Остаток по фактическому расходу",
  },
  thuLibrary: {
    title: "Ведомости ТХУ-3",
    description:
      "Заполняй ведомость ТХУ-3 общей шапкой и одной или несколькими операциями внутри неё.",
    add: "Добавить ведомость",
    edit: "Редактировать ведомость",
    empty: "Ведомостей ТХУ-3 пока нет.",
    documentNumber: "Номер ТХУ-3",
    shiftStart: "Начало смены",
    shiftEnd: "Окончание смены (время)",
    operationType: "Вид операции",
    operationStart: "Начало операции (время)",
    operationEnd: "Окончание операции (время)",
    operationTypes: {
      idle: "Прогрев",
      maneuvers: "Прогрев",
      depotHeating: "Прогрев",
      stationHeating: "Прогрев",
      fueling: "Экипировка",
    },
    section: (index: number) => `Секция ${index}`,
    series: "Серия",
    locomotiveNumber: "Номер тепловоза",
    sectionNumber: "Номер секции",
    fuelAtStart: "Топливо при приёмке, кг",
    fuelAtEnd: "Топливо при сдаче, кг",
    fuelAdded: "Набрано топлива, кг",
    addSection: "Добавить секцию",
    removeSection: "Удалить секцию",
    save: "Сохранить ведомость",
    cancel: "Отмена",
    delete: "Удалить",
    editAction: "Изменить",
    invalidPeriod:
      "Проверь время: операция и смена должны иметь положительную длительность, а операция — находиться внутри смены.",
    shiftTooLong: "Продолжительность смены не может превышать 12 часов.",
    requiredFields: "Заполни основные поля и данные каждой секции.",
    fuelDecrease:
      "При сдаче топлива должно быть не больше, чем при приёмке.",
    fuelingMismatch:
      "Для экипировки разница между сдачей и приёмкой должна совпадать с количеством набранного топлива.",
    storageError:
      "Не удалось открыть локальное хранилище документов. Перезапусти приложение и попробуй снова.",
    sectionsCount: (count: number) => `${count} секц.`,
    inheritedLocomotive: "Серия и номер будут взяты из первой секции.",
    hotIdle: "Горячий простой",
  },
  mmLibrary: {
    title: "Маршруты машиниста",
    description:
      "Создавай маршруты с посекционным топливом и автоматически рассчитанной таксировкой.",
    add: "Добавить маршрут",
    edit: "Редактировать маршрут",
    empty: "Маршрутов машиниста пока нет.",
    routeNumber: "Номер маршрута",
    driverName: "Фамилия машиниста (необязательно)",
    departureStation: "Станция отправления",
    arrivalStation: "Станция прибытия",
    addStation: "Добавить станцию",
    noStation: "Не указана",
    newStation: "Новая станция",
    callTime: "Явка",
    routeStart: "Сдача предыдущей бригады",
    routeEnd: "Сдача тепловоза (время или дата и время)",
    routeEndPlaceholder: "18:30, 1830, 16.06.26 18:30 или 1606261830",
    zeroRoute: "Нулевой ММ",
    zeroRouteHint:
      "Норма будет автоматически равна факту, результат останется нулевым.",
    normFuel: "Норма по таксировке, кг",
    actualFuel: "Фактический расход",
    taxationResult: "Результат таксировки",
    economy: "Зачётная экономия",
    overrun: "Пережог",
    zero: "Ноль",
    section: (index: number) => `Секция ${index}`,
    series: "Серия",
    locomotiveNumber: "Номер тепловоза",
    sectionNumber: "Номер секции",
    fuelAtStart: "Топливо при приёмке, кг",
    fuelAtEnd: "Топливо при сдаче, кг",
    addSection: "Добавить секцию",
    removeSection: "Удалить секцию",
    save: "Сохранить маршрут",
    cancel: "Отмена",
    delete: "Удалить",
    editAction: "Изменить",
    requiredFields: "Заполни данные маршрута и каждой секции.",
    invalidPeriod: "Время сдачи должно быть позже начала маршрута.",
    fuelDecrease:
      "При сдаче топлива должно быть не больше, чем при приёмке.",
    normError: "Введи норму расхода.",
    storageError:
      "Не удалось открыть локальное хранилище маршрутов. Перезапусти приложение и попробуй снова.",
    sectionsCount: (count: number) => `${count} секц.`,
    inheritedLocomotive: "Серия и номер будут взяты из первой секции.",
    withoutDriver: "Без фамилии",
  },
  chains: {
    title: "Топливные цепочки",
    description:
      "Собери рабочий кусок многолетней истории локомотива из ТХУ-3 и ММ. При разрыве кусок можно расширить соседними документами.",
    add: "Собрать кусок",
    edit: "Расширить кусок",
    empty: "Топливных цепочек пока нет.",
    noDocuments:
      "Сначала создай хотя бы два документа ТХУ-3 или ММ.",
    titleLabel: "Название цепочки",
    autoTitlePrefix: "Цепочка",
    tankCapacity: "Лимит бака, кг (необязательно)",
    tankCapacityError: "Введи положительный лимит вместимости бака.",
    documents: "Документы цепочки",
    documentsDescription:
      "Добавляй только нужный участок истории. Если для устранения разрыва не хватает соседних документов, расширь кусок через поиск.",
    searchDocuments: "Поиск документов",
    searchPlaceholder: "Тепловоз, дата, номер ТХУ/ММ, станция",
    selectedDocuments: "В текущем куске",
    noSelectedDocuments: "Документы ещё не добавлены.",
    availableDocuments: "Добавить документы",
    addDocumentsToPiece: "Расширить кусок",
    newThuForGap: "Новая ТХУ-3",
    createThu: "Создать ТХУ-3",
    createRoute: "Создать ММ",
    addDocument: "Добавить",
    removeDocument: "Убрать документ",
    documentsNotFound: "По этому запросу документов не найдено.",
    selectAtLeastTwo: "Выбери не менее двух документов.",
    save: "Сохранить цепочку",
    cancel: "Отмена",
    delete: "Удалить",
    editAction: "Изменить",
    storageError:
      "Не удалось открыть локальное хранилище цепочек.",
    thu: "ТХУ-3",
    driverRoute: "ММ",
    timeGap: "Разрыв времени",
    timeOverlap: "Перекрытие времени",
    timeContinuous: "Время непрерывно",
    transition: "Переход",
    fuelGap: "Разрыв топлива",
    fuelContinuous: "Топливо непрерывно",
    sectionMissing: "Секция отсутствует в одном из документов",
    locationGap: "Разрыв дислокации",
    locationContinuous: "Дислокация сходится",
    locationMissing: "Дислокация указана не полностью",
    locationUnknown: "Станция не указана",
    breakFound: "Есть разрыв",
    createThuSuggestion: (period: string) =>
      `Оформить на промежуток ${period}. В соседние ТХУ-3 это время не помещается.`,
    chainIsContinuous: "Разрывов между документами не найдено.",
    hotIdle: "Общий горячий простой",
    heatingTime: "Время прогрева",
    totalFuel: "Общий расход",
    fuelPerHour: "Удельный расход",
    documentsCount: (count: number) => `${count} док.`,
    linksCount: (count: number) => `${count} переходов`,
    sectionLabel: (key: string) => key.replaceAll("|", "-"),
    correct: "Корректировать",
    correctionTitle: "Ручная корректировка",
    correctionDescription:
      "Исходные документы не изменяются. Здесь формируется черновик исправлений для бумажных ведомостей.",
    correctionFocusTitle: "Где разрыв",
    selectedBreakTitle: "Проблемное место",
    neededTime: "Нужно закрыть время",
    neededFuel: "Нужно свести топливо",
    noSelectedBreak: "Выбери разрыв в цепочке сверху.",
    manualFields: "Ручные поля",
    scenariosTitle: "Автосценарии",
    scenarioApply: "Применить",
    scenarioUnavailable: "Недоступно",
    scenarioChanges: (count: number) => `${count} правок`,
    scenarios: {
      "close-gaps": {
        title: "Сохранить горячий простой",
        description:
          "Закрыть топливные разрывы так, чтобы не увеличивать горячий простой.",
      },
      "protect-routes": {
        title: "Беречь ММ",
        description:
          "По возможности исправлять ТХУ-3, чтобы меньше менять результат маршрута.",
      },
      balanced: {
        title: "Разделить разницу",
        description:
          "Разнести топливную поправку между соседними документами поровну.",
      },
    },
    operationStartAfter: "Начало операции — стало",
    operationEndAfter: "Окончание операции — стало",
    fuelStartAfter: "Топливо при приёмке — стало",
    fuelEndAfter: "Топливо при сдаче — стало",
    routeTimeLocked: "Время ММ зафиксировано и не изменяется.",
    before: "Было",
    after: "Стало",
    afterCorrection: "Цепочка после корректировки",
    paperInstructions: "Инструкция для бумаги",
    noCorrections: "Изменений пока нет.",
    saveDraft: "Сохранить черновик",
    resetDraft: "Сбросить изменения",
    draftSaved: "Черновик корректировки сохранён.",
  },
  settings: {
    title: "Настройки",
    description:
      "Норматив нужен для сравнения фактического расхода с плановым.",
    normLabel: "Норматив удельного расхода, кг/ч",
    normPlaceholder: "Например 45,0",
    normError: "Введи норматив от 0 до 9999,999 кг/ч.",
    saveNorm: "Сохранить норматив",
    normSaved: "Норматив сохранён",
    normCleared: "Норматив очищен",
    appearanceTitle: "Оформление",
    appearanceDescription:
      "Выбери тему приложения или доверь выбор настройкам устройства.",
    layoutModeLabel: "Ориентация экрана",
    layoutMode: {
      portrait: "Портретная",
      landscape: "Альбомная",
    },
    inputTitle: "Ввод даты и времени",
    inputDescription:
      "Выбери удобный способ ввода для ТХУ-3 и ММ. Удобный ввод принимает несколько привычных форматов.",
    dateTimeInputModeLabel: "Формат ввода даты/времени",
    quickAccessTitle: "Панель быстрого доступа",
    quickAccessDescription:
      "Закрепи до четырёх разделов. Кнопка «Все» останется на панели всегда.",
    quickAccessLimit: "Можно закрепить не более четырёх разделов.",
    quickAccessMinimum: "Нужно оставить хотя бы один закреплённый раздел.",
    themeSelectorLabel: "Тема приложения",
    theme: {
      system: "Системная",
      light: "Светлая",
      dark: "Тёмная",
    },
    dateTimeInputMode: {
      friendly: "Удобный ввод",
      calendar: "С календарём",
      asu: "Как в ЕК АСУФР2",
    },
    slotsTitle: "Слоты сохранения",
    slotsDescription:
      "Здесь хранятся временные сохранения для экрана сложения.",
    slot: (index: number) => `Слот ${index}`,
    emptySlot: "Пустой",
    historyTitle: "История расчётов",
    historyDescription:
      "Постоянный журнал сохранённых результатов и исходных данных.",
    emptyHistory: "Сохранённых расчётов пока нет.",
    historyType: {
      byTime: "Расчёт по ТХУ-3",
      quick: "Быстрый расчёт",
      summary: "Сложение прогревов",
    },
    balances: "Остатки",
    time: "Время",
    fuel: "Топливо",
    chainStart: "Начало цепочки",
    deleteHistoryEntry: (title: string) => `Удалить запись ${title}`,
    calculationNorm: "Норма на момент расчёта",
    forPeriod: "за период",
    aboutTitle: "О приложении",
    githubTitle: "GitHub разработчика",
    developer: "Drunken Spark Dev",
    feedbackTitle: "Связаться с разработчиком",
    feedbackDescription:
      "Сообщи об ошибке, предложи улучшение или задай вопрос удобным способом.",
    emailTitle: "E-mail",
    emailDescription: "Написать на почту",
    telegramTitle: "Telegram",
    telegramDescription: "Написать в Telegram",
    expressTitle: "eXpress",
    expressDescription: "Написать в eXpress",
    supportTitle: "Поддержать разработчика",
    supportDescription:
      "Разработка - вещь доступная, но не бесплатная. Если приложение оказалось полезным, поддержи его автора копеечкой <3",
    supportButton: "Перейти к Яндекс Чаевым",
    installHint:
      "Установка на iPhone: открой приложение в Safari, нажми «Поделиться» и выбери «На экран Домой».",
  },
} as const;
